### ISSUE TITLE
Feature request: merge repos into one

### ISSUE THREAD

**Issue by QiangF** [pyroll-project/pyroll#1]
The whole project is split into too many small repos. It would be more convenient to follow the development if they can be merged.

Currently I rely on a script to merge them, you can see the inconsistency in the layout of each sub repo.

[command.py.txt](https://github.com/pyroll-project/pyroll/files/10930235/command.py.txt)

**Comment by axtimhaus** [comment]
Thanks for your feedback.

We split the development in many repositories to be able to maintain access rights particularly.
This is required for us, since not all repositories are public as they may be not allowed for us to be published.
So the current approach will be retained.

Each plugin has and will have it's own repository, as they are generally independent of each other. They main development resides however on `pyroll-core`, so if you have general questions or suggestions post it there. Topics targeting single plugins should be posted in the respective repository.

**Comment by QiangF** [comment]
I have made a repo using submules with symlinks here

    git@github.com:QiangF/pyroll-projects.git

Please let me know if it is inappropriate.
Thank you!
